
package Telas;

import DAO.Inseredados;
import DAO.LivroDAO;
import DAO.UsuarioDAO;
import conexao.Conexao;


public class TelaBase extends javax.swing.JFrame {


    public TelaBase() {
        initComponents();
        if(new Conexao().Conect()== null){
                new Conexao().CreateDB();
                new Inseredados().insere();
            } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        geral = new javax.swing.JComboBox<>();
        especifico = new javax.swing.JComboBox<>();
        busca = new javax.swing.JTextField();
        buscar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SISTEMA BIBLIOTECÁRIO");

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        geral.setBackground(new java.awt.Color(255, 255, 255));
        geral.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        geral.setForeground(new java.awt.Color(0, 0, 0));
        geral.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECIONE", "USUÁRIOS", "EXEMPLARES", "OBRAS" }));
        geral.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                geralItemStateChanged(evt);
            }
        });

        especifico.setBackground(new java.awt.Color(255, 255, 255));
        especifico.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        especifico.setForeground(new java.awt.Color(0, 0, 0));
        especifico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECIONE" }));
        especifico.setEnabled(false);
        especifico.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                especificoItemStateChanged(evt);
            }
        });

        busca.setBackground(new java.awt.Color(255, 255, 255));
        busca.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        busca.setForeground(new java.awt.Color(0, 0, 0));
        busca.setCaretColor(new java.awt.Color(0, 0, 0));
        busca.setEnabled(false);

        buscar.setBackground(new java.awt.Color(255, 255, 255));
        buscar.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        buscar.setForeground(new java.awt.Color(0, 0, 0));
        buscar.setText("PESQUISAR");
        buscar.setEnabled(false);
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Old English Text MT", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Sistema  Bibliotecário");

        jLabel4.setFont(new java.awt.Font("Gisha", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("TERMO GERAL:");

        jLabel5.setFont(new java.awt.Font("Gisha", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("TERMO ESPECÍFICO:");

        jLabel6.setFont(new java.awt.Font("Gisha", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("TERMO DE BUSCA:");

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(geral, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(especifico, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(busca, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buscar)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(geral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(especifico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(busca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(buscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(0, 102, 255));
        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        jPanel4.setBackground(new java.awt.Color(0, 102, 255));
        jPanel4.setLayout(new javax.swing.OverlayLayout(jPanel4));

        tabela.setBackground(new java.awt.Color(255, 255, 255));
        tabela.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tabela.setForeground(new java.awt.Color(0, 0, 0));
        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabela.setToolTipText("RESULTADOS");
        tabela.setGridColor(new java.awt.Color(153, 153, 153));
        tabela.setSelectionBackground(new java.awt.Color(0, 102, 204));
        tabela.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(tabela);

        jPanel4.add(jScrollPane1);

        jPanel3.add(jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 684, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void geralItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_geralItemStateChanged
        // TODO add your handling code here:
        switch (geral.getSelectedIndex()){
            case 0:
            especifico.removeAllItems();
            especifico.setEnabled(false);
            buscar.setEnabled(false);
            break;
            case 1: 
            especifico.removeAllItems();
            especifico.addItem("DADOS PESSOAIS");
            especifico.addItem("EMPRÉSTIMOS");
            especifico.addItem("Nº DE EMPRÉSTIMOS");
            especifico.addItem("Nº DE EMPRÉSTIMOS: (>=)");
            especifico.setEnabled(true);
            break;
            case 2:
            especifico.removeAllItems();
            especifico.addItem("TODOS");
            especifico.addItem("DISPONÍVEIS");
            especifico.addItem("INDISPONÍVEIS");
            especifico.setEnabled(true);
            break;
            case 3: 
            especifico.removeAllItems();
            especifico.addItem("Nº DE EXEMPLARES POR OBRA");
            especifico.addItem("OBRAS CADASTRADAS");
            especifico.addItem("OBRAS POR AUTOR");
            especifico.setEnabled(true);
            break;
        }
    }//GEN-LAST:event_geralItemStateChanged

    private void especificoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_especificoItemStateChanged
        // BUSCAS
        buscar.setEnabled(true);
        switch (especifico.getSelectedIndex()){
            case 0:
            if(geral.getSelectedIndex() == 1){
                tabela.setModel(new javax.swing.table.DefaultTableModel(
                    new Object [][] {},
                    new String [] {
                        "NOME", "CPF", "RG", "EMAIL", "TELEFONE", "LOGRADOURO","BAIRRO","N°","CIDADE"}));
            busca.setText("");
            busca.setEnabled(true);}
        if(geral.getSelectedIndex() == 3){
            tabela.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {},
                new String [] {
                    "TÍTULO DA OBRA", "EXEMPLARES CADASTRADOS"}));
        busca.setText("");
        busca.setEnabled(true);}
        if(geral.getSelectedIndex() == 2){
            tabela.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {},
                new String [] {
                    "N° EXEMPLAR", "TÍTULO", "AUTOR", "EDIÇÃO", "ANO", "STATUS"}));
        busca.setText("");
        busca.setEnabled(true);}

        break;
        case 1:
        if(geral.getSelectedIndex() == 1){
            tabela.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {},
                new String [] {
                    "NOME DO USUÁRIO", "DATA DO EMPRÉSTIMO","TÍTULO", "AUTOR", "ISBN"}));
        busca.setText("");
        busca.setEnabled(true);}

        if(geral.getSelectedIndex() == 2){
            tabela.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {},
                new String [] {
                    "N° EXEMPLAR","ISBN", "TÍTULO", "AUTOR", "EDITORA","ANO"}));
        busca.setText("");
        busca.setEnabled(true);}
        if(geral.getSelectedIndex() == 3){
            tabela.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {},
                new String [] {
                    "ISBN","TÍTULO", "AUTOR", "EDITORA","ANO"}));
        busca.setText("");
        busca.setEnabled(true);}  //isbn, titulo, autor, editora, ano
        break;
        case 2:
        if(geral.getSelectedIndex() == 1){
            tabela.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {},
                new String [] {
                    "NOME DO USUÁRIO","N° DE EMPRÉSTIMOS"}));
        busca.setText("");
        busca.setEnabled(true);}
        if(geral.getSelectedIndex() == 2){
            tabela.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {},
                new String [] {
                    "N° EXEMPLAR", "ISBN", "TÍTULO", "AUTOR", "EDITORA","ANO"}));
        busca.setText("");
        busca.setEnabled(true);}
        if(geral.getSelectedIndex() == 3){
            tabela.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {},
                new String [] { // AUTOR, TITULO, EDITORA, ANOPUB, ISBN
                    "AUTOR DA OBRA", "TÍTULO", "EDITORA", "ANO","ISBN"}));
        busca.setText("");
        busca.setEnabled(true);}
        break;
        case 3: 
            if(geral.getSelectedIndex() == 1){
            tabela.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {},
                new String [] {
                    "NOME DO USUÁRIO","N° DE EMPRÉSTIMOS"}));
        busca.setText("");
        busca.setEnabled(true);}
            break;
        }
    }//GEN-LAST:event_especificoItemStateChanged

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed

        if(geral.getSelectedIndex() == 3 && especifico.getSelectedIndex()== 0 ){
            new LivroDAO().ConsultaLivro(new Conexao().Conect(), tabela,busca.getText()); }
        if(geral.getSelectedIndex() == 3 && especifico.getSelectedIndex()==1){
            new LivroDAO().ConsultaSimples(new Conexao().Conect(), tabela,busca.getText());}
        if(geral.getSelectedIndex() == 3 && especifico.getSelectedIndex()==2){
            new LivroDAO().ConsultaPorAutor(new Conexao().Conect(), tabela,busca.getText());}
        if(geral.getSelectedIndex() == 1 && especifico.getSelectedIndex()==0){
            new UsuarioDAO().ConsultaUserP(new Conexao().Conect(), tabela,busca.getText());}
        if(geral.getSelectedIndex() == 1 && especifico.getSelectedIndex()==1){
            new UsuarioDAO().ConsultaEmp(new Conexao().Conect(), tabela, busca.getText());}
        if(geral.getSelectedIndex() == 1 && especifico.getSelectedIndex()==2){
            new UsuarioDAO().ConsultaNemp(new Conexao().Conect(), tabela,busca.getText());}
        if(geral.getSelectedIndex() == 1 && especifico.getSelectedIndex()==3){
            new UsuarioDAO().ConsultaHaving(new Conexao().Conect(), tabela,Integer.parseInt(busca.getText()));}
        if(geral.getSelectedIndex() == 2 && especifico.getSelectedIndex()== 0){
            new LivroDAO().ConsultaEx(new Conexao().Conect(), tabela,busca.getText());}
        if(geral.getSelectedIndex() == 2 && especifico.getSelectedIndex()==1){
            new LivroDAO().ConsultaLivrosDisp(new Conexao().Conect(), tabela,busca.getText());}
        if(geral.getSelectedIndex() == 2 && especifico.getSelectedIndex()==2){
            new LivroDAO().ConsultaLivrosInd(new Conexao().Conect(), tabela,busca.getText());}
         
    }//GEN-LAST:event_buscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaBase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaBase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaBase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaBase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaBase().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField busca;
    private javax.swing.JButton buscar;
    private javax.swing.JComboBox<String> especifico;
    private javax.swing.JComboBox<String> geral;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
